#ifndef MQL_AUTO_FORWARDS_INCLUDED_D5CF4C637E2B0F54
#define MQL_AUTO_FORWARDS_INCLUDED_D5CF4C637E2B0F54
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5

#line 99 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void TryConnect();
#line 118 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SendHello();
#line 134 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SendSymbolList();
#line 154 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void DrainMessages();
#line 177 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleMessage(CJson &msg);
#line 207 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
bool ExecuteMarketOrder(const string side, const string symbol, const double volume, const double sl, const double tp, ulong &out_ticket);
#line 224 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SendOrderResult(const string id, const bool ok, const ulong ticket, const string error, const int closed_count = -1);
#line 238 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleSignal(CJson &msg);
#line 262 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleOpenOrder(CJson &msg);
#line 276 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleClosePosition(CJson &msg);
#line 285 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
bool CloseTicketReliable(const ulong ticket);
#line 305 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleCloseAll(CJson &msg);
#line 316 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleModifyPosition(CJson &msg);
#line 331 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleSetMagic(CJson &msg);
#line 339 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
ENUM_TIMEFRAMES StringToTimeframe(const string tf);
#line 358 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void HandleGetHistory(CJson &msg);
#line 405 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SendPositionsSnapshot();
#line 448 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SendAccountInfo();
#line 468 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SyncClosedDeals();
#line 500 "/Users/thuanvu/Documents/PyGay/mql5/Experts/SocketBridgeEA.mq5"
void SendClosedDeal(const long position_id);

#endif
